blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/hyrated117-svg/Cloudflare-Network-Diagnostic-Tool-v1.0-cd9381bb/discussions
    about: For general questions and discussions
  - name: Security Issues
    url: https://github.com/hyrated117-svg/Cloudflare-Network-Diagnostic-Tool-v1.0-cd9381bb/security/advisories
    about: Please report security vulnerabilities responsibly
